branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: circleci-beanstalk-dev
environment-defaults:
  circleci-beanstalk-dev:
    branch: null
    repository: null
global:
  application_name: circleci-beanstalk
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
